### ISSUE TITLE
Gui Fix!

### ISSUE THREAD

**Issue by SecretSnake55** [ArtixAllMighty/Telepads#4] opened 2015-04-19 09:03 UTC
Please update and fix the gui render size to be current! gui size 
Thanks

**Comment by darkhax** [comment] 2015-10-03 21:59
Given that this mod is being rewritten, I will close this issue. If the issue is still found in the latest release (which is not yet out) please re-open this issue.

**Closed by darkhax** 2015-10-03 21:59 UTC
